"""Check the committed HTML still matches what build_gallery.py generates.

Why this exists: on 2026-08-12 a rebuild from a stale clone on another machine overwrote
v2-imageled.html and silently reverted the blue masthead and the wider article spacing. The
preview site served the wrong thing for a week. The HTML and the build script drifted apart and
nothing complained.

Run this after pulling, and before pushing any rebuild:

    python project/check_sync.py

Exits non-zero and prints a diff if they have drifted. build_gallery.py writes to a hardcoded
Windows path, so rather than running it we import it with the file writes intercepted.

Needs: nothing beyond the standard library.
"""
import os
import re
import sys
import difflib

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def generate():
    """Run build_gallery.py in-process and return {filename: content} instead of writing."""
    src = open(os.path.join(HERE, "build_gallery.py"), encoding="utf-8").read()
    src = re.sub(r'^EMAIL_DIR = .*$', 'EMAIL_DIR = "."', src, flags=re.M)
    src = re.sub(r'^open\(os\.path\.join\(EMAIL_DIR,"(.+?)"\).*?\.write\((.+?)\)$',
                 lambda m: f'captured["{m.group(1)}"] = {m.group(2)}', src, flags=re.M)
    # v3/v4 are copied from files that only exist on the original build machine.
    src = re.sub(r'^(shutil\..*|import shutil.*)$', 'pass', src, flags=re.M)
    # Skip the build script's own staleness guard: we only want to compare content here,
    # not hit the network or exit on behalf of the caller.
    src = re.sub(r'^_abort_if_stale\(\)$', 'pass', src, flags=re.M)
    captured = {}
    exec(compile(src, "build_gallery.py", "exec"), {"__name__": "notmain", "captured": captured})
    return captured


def main():
    generated = generate()
    drifted = []
    for name, content in sorted(generated.items()):
        path = os.path.join(ROOT, name)
        if not os.path.exists(path):
            print(f"MISSING  {name}")
            drifted.append(name)
            continue
        on_disk = open(path, encoding="utf-8").read()
        if on_disk.strip() == content.strip():
            print(f"ok       {name}")
        else:
            print(f"DRIFTED  {name}")
            drifted.append(name)
            for line in list(difflib.unified_diff(
                    on_disk.splitlines(), content.splitlines(),
                    "committed", "generated by build_gallery.py", lineterm=""))[:14]:
                print("         " + line[:130])

    if drifted:
        print(f"\n{len(drifted)} file(s) out of sync with build_gallery.py: {', '.join(drifted)}")
        print("Regenerate from the script, or port the hand-edit back into it. Do not push as-is.")
        return 1
    print("\nAll generated files match build_gallery.py.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
